from django.contrib import admin
from .models import *
admin.site.register(Category)
admin.site.register(ProductPhoto)
admin.site.register(ProductInfo)
admin.site.register(Product)
admin.site.register(Service)
admin.site.register(Blog)
admin.site.register(Emails)
admin.site.register(Info)
admin.site.register(Team)
admin.site.register(ClientSays)
admin.site.register(Partner)
admin.site.register(OurStories)
admin.site.register(Faq)
admin.site.register(Card)
admin.site.register(Wishlist)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(Contact)
