# Generated by Django 4.1.5 on 2023-02-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_card_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
