# Generated by Django 4.1.5 on 2023-02-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='quantity',
        ),
    ]
